// GENERATED BY glcean
// This file was generated by robots at
// {{ .TimeStamp }}

package models
{{/*
{{index $.Attributes   2}}.Type
	*/}}

type {{.ModelName}} struct {
	{{ range $i,$att :=  .Attributes -}}
	 {{  $att.Name | camelcase    }}  {{$att.Type}}  `json:"{{$att.Name | snakecase}}"`
	{{ end -}}
}
